// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjD5EpU3ksRN2YdWdLRCNtKfxXTwi1ORc',
    appId: '1:146899159029:web:7f8d8fba1af7c125acc2bc',
    messagingSenderId: '146899159029',
    projectId: 'kitchen-order-app',
    authDomain: 'kitchen-order-app.firebaseapp.com',
    storageBucket: 'kitchen-order-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQGoyeeXHhf7_XQVQpF4_AOGyAAqAjow',
    appId: '1:146899159029:android:f1090b87fde4880facc2bc',
    messagingSenderId: '146899159029',
    projectId: 'kitchen-order-app',
    storageBucket: 'kitchen-order-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4JWUPw_GhFOn6GlTIfu8deTgTcG8kX4',
    appId: '1:146899159029:ios:01279bad4b57426eacc2bc',
    messagingSenderId: '146899159029',
    projectId: 'kitchen-order-app',
    storageBucket: 'kitchen-order-app.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrderMgmtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4JWUPw_GhFOn6GlTIfu8deTgTcG8kX4',
    appId: '1:146899159029:ios:01279bad4b57426eacc2bc',
    messagingSenderId: '146899159029',
    projectId: 'kitchen-order-app',
    storageBucket: 'kitchen-order-app.firebasestorage.app',
    iosBundleId: 'com.example.kitchenOrderMgmtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjD5EpU3ksRN2YdWdLRCNtKfxXTwi1ORc',
    appId: '1:146899159029:web:9138a52c01a11b80acc2bc',
    messagingSenderId: '146899159029',
    projectId: 'kitchen-order-app',
    authDomain: 'kitchen-order-app.firebaseapp.com',
    storageBucket: 'kitchen-order-app.firebasestorage.app',
  );
}
